config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get 'search' # Adiciona uma rota para a ação "search"
    end
  end

  # Resto das rotas...

  # Define a rota root ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  # validação do email: formato aceito : conter o @, e pelomenos 1 caracter antes dele
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ }
  # validação do cpf : formato aceito : 11 numeros
  validates :cpf, presence: true, uniqueness: true, format: { with: /\A\d{11}\z/ }
  # Validação do telefone: formato aceito (xx)xxxxx-xxxx
  validates :phone, presence: true, format: { with: /\A\(\d{2}\)\d{5}-\d{4}\z/ }

  # lembrando que tambem o usuario nao pode ser criado com algum atributo repetido ,exemplo o email e cpf nao podem ser iguais a de outros usuarios
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

    # GET /users or /users.json

    def index
      @users = User.all
  
      if params[:search].present?
        search_term = "%#{params[:search]}%"
        @users = @users.where("name LIKE :term OR email LIKE :term OR phone LIKE :term OR cpf LIKE :term", term: search_term)
      else
        flash.now[:error] = "Por favor, insira um termo de pesquisa."
      end
    end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "Usuário criado com sucesso !" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "Usuário editado com sucesso!" }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "Usuário deletado com sucesso!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :phone, :cpf)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoFestalab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="principal">
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %>  proibiram este usuário de ser salvo:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-container">

<div class="form-field">
  <%= form.label :nome, class: "form-label" %>
  <%= form.text_field :name, class: "form-input" %>
</div>

<div class="form-field">
  <%= form.label :email, class: "form-label" %>
  <%= form.text_field :email, class: "form-input" %>
</div>

<div class="form-field">
  <%= form.label :Telefone, class: "form-label" %>
  <%= form.text_field :phone, class: "form-input" %>
</div>

<div class="form-field">
  <%= form.label :CPF, class: "form-label" %>
  <%= form.text_field :cpf, class: "form-input" %>
</div>

<div class="form-actions">
  <%= form.submit "Criar", class: "btn-submit" %>
</div>

</div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Nome:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= user.phone %>
  </p>

  <p>
    <strong>CPF:</strong>
    <%= user.cpf %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editar Usuário</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Mostrar esse usuário", @user %> |
  <%= link_to "Voltar para listagem de usuários", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% if flash[:error] %>
  <div class="alert ">
    <%= flash[:error] %>
  </div>
<% end %>
<%= form_tag(users_path, method: :get, class: "form-inline mb-3") do %>
  <div class="form-group mr-2">
    <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Pesquise por qualquer campo" %>
    <%= submit_tag "Pesquisar", class: "btn btn-primary" %>
    <%= link_to "Novo usuário", new_user_path , class: "btn btn-primary" %>
  </div>
  <div class="form-group">
  </div>
<% end %>

<h1>Usuários</h1> 

<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>CPF</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.cpf %></td>
       <td>
        <%= link_to "Detalhes", user %>
       
       </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%
=begin%>
 <div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Mostrar esse usuário", user %>
    </p>
  <% end %> 
<%
=end%>
</div>

app/views/users/new.html.erb
<div class="form-container">
<h1>Novo usuário</h1>
<%= render "form", user: @user  %>
<div class="back-link">
  <%= link_to "Voltar para a listagem de usuários", users_path %>
</div>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="form-container">


<%= render @user %>

<div>
  <%= link_to "Editar esse usuário",edit_user_path(@user) %> |
  <%= link_to "Voltar para listagem de usuários", users_path %>
<br>
  <%= button_to "Excluir esse usuário", @user, method: :delete ,class:"btn btn-primary"  %>
</div>
</div>